### ISSUE TITLE
I need yout help

### ISSUE THREAD

**Issue by AbelolDev** [AbelolDev/Bono-DB-Manager#1]
I am looking to add more functions to the library and also to have an English version of the code.

**Comment by Suhaib1278** [comment]
Hi @AbelolDev if you're still working on this project, I'd be happy to contribute. Let me know and we can connect

**Comment by AbelolDev** [comment]
Hello, if the project I still plan to update it just because of time and studies I have not been able to give the necessary time, so if I can count on your collaboration I would be delighted.

**Comment by Suhaib1278** [comment]
Lets connect on LinkedIn and we can discuss it further

**Comment by AbelolDev** [comment]
I'm sorry, but I would prefer another channel of communication.

**Comment by Suhaib1278** [comment]
No worries let me know how we can connect @AbelolDev

**Comment by AbelolDev** [comment]
Discord

**Comment by Suhaib1278** [comment]
Send me your discord I’ll add you Sent from my iPhoneOn 5 Sep 2024, at 23:13, AbelolDev ***@***.***> wrote:﻿
Discord

**Comment by AbelolDev** [comment]
Perfect

**Comment by Suhaib1278** [comment]
my discord: sting6543
